/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import java.awt.Color;
import javax.swing.ImageIcon;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

///Ez új!

import java.util.ArrayList;
import java.util.List;

/**
 *  Generates the MainGUI, and calls the api to Hungary with the current date
 * 
 * @author Yama
 */
public class mainGUI extends javax.swing.JFrame {
    private List<String> countries = new ArrayList<String>();
    private List<Integer> dailyStatsInfected = new ArrayList<>();
    private List<Integer> dailyStatsDeaths = new ArrayList<>();
    private String selectedCountry;
    private String date1;
    private String date2;
    /**
     * Creates new form mainGUI
     */
    public mainGUI() {
        initComponents();
        AutoCompleteDecorator.decorate(countrySelector);
        jPanel4.setVisible(false);
        fromDate.setDate(java.sql.Date.valueOf(java.time.LocalDate.now()));
        tillDate.setDate(java.sql.Date.valueOf(java.time.LocalDate.now()));
        //System.out.println(java.sql.Date.valueOf(java.time.LocalDate.now()));
        countrySelector.setSelectedItem("Hungary");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logoLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        countrySelector = new javax.swing.JComboBox<>();
        numberOfInfectedLabel = new javax.swing.JLabel();
        numberOfDeceased = new javax.swing.JLabel();
        numberOfDeceasedLabel = new javax.swing.JLabel();
        numberOfInfected = new javax.swing.JLabel();
        darkModeBtn = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        fromDate = new com.toedter.calendar.JDateChooser();
        countrySearchBtn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        regionSearchBtn = new javax.swing.JButton();
        countrySelector1 = new javax.swing.JComboBox<>();
        tillDate = new com.toedter.calendar.JDateChooser();
        jPanel5 = new javax.swing.JPanel();
        graphPanel = new javax.swing.JPanel();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox1 = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(192, 226, 238));
        setBounds(new java.awt.Rectangle(0, 0, 1024, 800));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(192, 226, 238));
        jPanel1.setPreferredSize(new java.awt.Dimension(914, 87));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoLabel.setFont(new java.awt.Font("Microsoft JhengHei", 1, 36)); // NOI18N
        logoLabel.setForeground(new java.awt.Color(193, 240, 219));
        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LogoB.png"))); // NOI18N
        jPanel1.add(logoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel2.setBackground(new java.awt.Color(192, 226, 238));

        countrySelector.setBackground(new java.awt.Color(51, 51, 51));
        countrySelector.setEditable(true);
        countrySelector.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        countrySelector.setForeground(new java.awt.Color(102, 102, 102));
        countrySelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countrySelectorActionPerformed(evt);
            }
        });

        numberOfInfectedLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        numberOfInfectedLabel.setText("Fertőzöttek száma(összes): ");

        numberOfDeceased.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        numberOfDeceased.setForeground(new java.awt.Color(255, 0, 0));
        numberOfDeceased.setText("123123123");

        numberOfDeceasedLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        numberOfDeceasedLabel.setText("Halottak száma(összes):");

        numberOfInfected.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        numberOfInfected.setText("123123123");

        darkModeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/DarkMode.png"))); // NOI18N
        darkModeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                darkModeBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Ország kiválasztása:");

        jPanel3.setBackground(new java.awt.Color(192, 226, 238));

        fromDate.setDateFormatString("y-MM-d");
        fromDate.setMinimumSize(new java.awt.Dimension(60, 30));
        fromDate.setPreferredSize(new java.awt.Dimension(95, 30));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(fromDate, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(fromDate, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        countrySearchBtn.setBackground(new java.awt.Color(102, 102, 102));
        countrySearchBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        countrySearchBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        countrySearchBtn.setToolTipText("");
        countrySearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countrySearchBtnActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(192, 226, 238));

        regionSearchBtn.setBackground(new java.awt.Color(102, 102, 102));
        regionSearchBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        regionSearchBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        regionSearchBtn.setToolTipText("");
        regionSearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regionSearchBtnActionPerformed(evt);
            }
        });

        countrySelector1.setBackground(new java.awt.Color(51, 51, 51));
        countrySelector1.setEditable(true);
        countrySelector1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        countrySelector1.setForeground(new java.awt.Color(102, 102, 102));
        countrySelector1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countrySelector1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(countrySelector1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(regionSearchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(regionSearchBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
            .addComponent(countrySelector1, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        tillDate.setDateFormatString("y-MM-d");
        tillDate.setMinimumSize(new java.awt.Dimension(60, 30));
        tillDate.setPreferredSize(new java.awt.Dimension(95, 30));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tillDate, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(darkModeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(286, 286, 286)
                                        .addComponent(countrySearchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(countrySelector, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(numberOfInfectedLabel)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(numberOfDeceasedLabel)
                                            .addComponent(numberOfInfected)
                                            .addComponent(numberOfDeceased))))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(countrySearchBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(countrySelector, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tillDate, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(numberOfInfectedLabel)
                .addGap(18, 18, 18)
                .addComponent(numberOfInfected)
                .addGap(18, 18, 18)
                .addComponent(numberOfDeceasedLabel)
                .addGap(18, 18, 18)
                .addComponent(numberOfDeceased)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 295, Short.MAX_VALUE)
                .addComponent(darkModeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel5.setBackground(new java.awt.Color(192, 226, 238));

        graphPanel.setBackground(new java.awt.Color(255, 255, 255));

        jCheckBox2.setText("Show Infected");
        jCheckBox2.setToolTipText("");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        jCheckBox1.setText("Show Deceased");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout graphPanelLayout = new javax.swing.GroupLayout(graphPanel);
        graphPanel.setLayout(graphPanelLayout);
        graphPanelLayout.setHorizontalGroup(
            graphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(graphPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(graphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox2)
                    .addComponent(jCheckBox1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        graphPanelLayout.setVerticalGroup(
            graphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(graphPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBox2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Lorem ipsum dolor, sit amet consectetur adipisicing elit. Impedit expedita recusandae porro delectus at id accusantium adipisci hic saepe? Numquam totam ex aut dolorum saepe sequi odio distinctio recusandae eveniet.");
        jTextArea1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(graphPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(graphPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1368, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Turns Night mode on or off
     * 
     * @author Patrik
     * @param evt An event
     */
    private void darkModeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_darkModeBtnActionPerformed
        setMode();
    }//GEN-LAST:event_darkModeBtnActionPerformed

/**
     * Hides and reveals the region panel and fills it up if the country has regions accordingly
     * 
     * @author Patrik
     * @param evt combobox selected item changed
     */
    private void countrySelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countrySelectorActionPerformed

    }//GEN-LAST:event_countrySelectorActionPerformed

    private void countrySearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countrySearchBtnActionPerformed

    }//GEN-LAST:event_countrySearchBtnActionPerformed

    private void regionSearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regionSearchBtnActionPerformed
        
    }//GEN-LAST:event_regionSearchBtnActionPerformed

    private void countrySelector1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countrySelector1ActionPerformed

    }//GEN-LAST:event_countrySelector1ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed

    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed

    }//GEN-LAST:event_jCheckBox2ActionPerformed
  
    /**
     * Decides wether to turn on Night or Light mode
     * 
     * @author Patrik
     */
     private void setMode(){
        boolean selected = darkModeBtn.isSelected();                
        if (selected){
            setDark();
        }
        else {
            setLight();
        }
    }
    /**
     * Enables dark mode, by setting the background colors of elements
     * 
     * Also switches the image to the correct one
     * 
     * @author Patrik
     */
    private void setDark(){
        Color darkmodeColor = new Color(19, 3, 64);

        darkModeBtn.setIcon(new ImageIcon(getClass().getClassLoader().getResource("\\images\\LightMode.png")));
        logoLabel.setIcon(new ImageIcon(getClass().getClassLoader().getResource("\\images\\LogoW.png")));
            
        graphPanel.setBackground(Color.black);
        jPanel2.setBackground(darkmodeColor);
        jPanel1.setBackground(darkmodeColor);
        jPanel5.setBackground(darkmodeColor);
        jPanel3.setBackground(darkmodeColor);
        jPanel4.setBackground(darkmodeColor);
            
        numberOfInfectedLabel.setForeground(Color.white);
        jLabel1.setForeground(Color.white);
        numberOfDeceasedLabel.setForeground(Color.white);
        numberOfInfected.setForeground(Color.white);
            
            
        jTextArea1.setBackground(Color.black);
        jTextArea1.setForeground(Color.white);
    }
    
    /**
     * Enables dark mode, by setting the background colors of elements
     * 
     * Also switches the image to the correct one
     * 
     * @author Patrik
     */
    private void setLight(){
        int r = 192;
        int g = 226;
        int b = 238;
        Color color = new Color(r,g,b);       
        darkModeBtn.setIcon(new ImageIcon(getClass().getClassLoader().getResource("\\images\\DarkMode.png")));
        logoLabel.setIcon(new ImageIcon(getClass().getClassLoader().getResource("\\images\\LogoB.png")));
            
        graphPanel.setBackground(Color.white);
        jPanel2.setBackground(color);
        jPanel1.setBackground(color);
        jPanel5.setBackground(color);
        jPanel3.setBackground(color);
        jPanel4.setBackground(color);    
        
        numberOfInfectedLabel.setForeground(Color.black);
        jLabel1.setForeground(color.black);
        numberOfDeceasedLabel.setForeground(Color.black);
        numberOfInfected.setForeground(Color.black);
            
        jTextArea1.setBackground(Color.white);
        jTextArea1.setForeground(Color.black);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainGUI().setVisible(true);
            }
        });
    }

    /**
     * Elements of the UI:
     * <pre>
     * jFrame:
     *      jPanel1: The upmost panel in the application
     *          jLabel2: Currently the name of our group
     *      jPanel2: The panel that's located on the left side of the screen, it contains the number of cases, death count, and the country list
     *          jCombobox1: Stores the available countries
     *          jLabel3: "Number of confirmed cases(all)"
     *          numberOfInfected: the current number of infected people in the selected country
     *          jLabel5: "Death count(all)"
     *          numberOfDeceased: the current number of deceased people in the selected country
     *          jToggleButton1: Toggles the night and light mode of the application
     *          jLabel1: "Select a country:"
     *      jPanel5: The right panel, that consists of displaying the graph, and the other calculated values
     *          jPanel6: This will store the drawn graph
     *              jLabel4: Currently a picture of a graph
     *          jScrollPane1: Holds the TextArea
     *              jTextArea: This will display the other calculated values
     * </pre>
     * 
     * @author T.Dani
     * @author Yama
    */
    private Boolean layout;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton countrySearchBtn;
    private javax.swing.JComboBox<String> countrySelector;
    private javax.swing.JComboBox<String> countrySelector1;
    private javax.swing.JToggleButton darkModeBtn;
    private com.toedter.calendar.JDateChooser fromDate;
    private javax.swing.JPanel graphPanel;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JLabel numberOfDeceased;
    private javax.swing.JLabel numberOfDeceasedLabel;
    private javax.swing.JLabel numberOfInfected;
    private javax.swing.JLabel numberOfInfectedLabel;
    private javax.swing.JButton regionSearchBtn;
    private com.toedter.calendar.JDateChooser tillDate;
    // End of variables declaration//GEN-END:variables
}
